### ISSUE TITLE
Add all team members

### ISSUE THREAD

**Issue by badboy** [badboy/barcelona.rustfest.eu#1]
We need pictures & names of the new ones.

**Comment by dns2utf8** [comment]
Did we complete this already?

**Comment by robertohuertasm** [comment]
Nope. Still some members pending.

**Comment by carlosb1** [comment]
I added my profile.

**Comment by alberss** [comment]
#26

**Comment by apiraino** [comment]
@robertohuertasm anyone else or can we close?

**Comment by robertohuertasm** [comment]
If we count some of the people in the CfP committe, then we're still missing `Núria Soriano` and `Juan Gómez`. I guess they should be here, too?

**Comment by apiraino** [comment]
> If we count some of the people in the CfP committe, then we're still missing `Núria Soriano` and `Juan Gómez`. I guess they should be here, too?

Historically, the Rustfest team and the CfP (a.k.a Program) team are separated (unless some do actual work to also organize the conference).

**Comment by robertohuertasm** [comment]
Then I guess you can close this. 👍
