### ISSUE TITLE
Question about the Spanish translations of diversity page

### ISSUE THREAD

**Issue by ifraixedes** [badboy/barcelona.rustfest.eu#17]
Hello,

In the last RustFest organizing meeting we agreed that I'm in charge of translating the diversity page.

I have a few questions in order of doing so:

* Which is exactly the page? 
 this one https://github.com/RustFestEU/barcelona.rustfest.eu/blob/gh-pages/accessibility.md ?
* How I create a localized Spanish version of the page in Jekyll?

**Comment by badboy** [comment]
It's this: https://github.com/RustFestEU/barcelona.rustfest.eu/blob/gh-pages/diversity.md

We don't really have an easy way to do localization, but my suggestion would be:

* Create a new file `diversity.es.md`
* In the front matter (copy it from the diversity.md) set the permalink to `/diversity/es`.
* Add a link to the top of diversity.md to link to the spanish version

**Comment by ifraixedes** [comment]
Thanks, I'll try to send a  PR soon.

I didn't find that page in the repo because I went to the website to try to find the link and then I came to the repo to look for it.

Out of curiosity how you can go to such page through the home page?

**Comment by badboy** [comment]
Policies -> Info -> Diversity at RustFest
(https://barcelona.rustfest.eu/info/)
